apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App2 Website</title>
    </head>
    <body>
      <h1>🚀 Welcome to App2</h1>
      <p>Hosted using NGINX on Kind Kubernetes Cluster</p>
    </body>
    </html>

