#################################### Server ####################################
[server]
protocol = http
http_port = 3000
domain = localhost
enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s/

#################################### Security ####################################
[security]
admin_user = admin
admin_password = admin

#################################### Users ####################################
[users]
default_theme = dark
allow_sign_up = false

#################################### Dashboards ####################################
[dashboards]
versions_to_keep = 20
min_refresh_interval = 1s

#################################### Dataproxy ####################################
[dataproxy]
logging = true

#################################### SMTP / Email Alerts ####################################
[smtp]
enabled = true
host = smtp.gmail.com:587
user = kathuriagagan96@gmail.com
password = bgun avsp qghg lmsd
skip_verify = false
from_address = kathuriagagan96@gmail.com
from_name = Grafana Alerts

#################################### Unified Alerting (Grafana v10+) ####################################
[unified_alerting]
enabled = true

#################################### Logging ####################################
[log]
mode = console
level = info

#################################### Analytics ####################################
[analytics]
reporting_enabled = false
check_for_updates = true

